### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [hugolgst/rich-go#31]

**Comment by hugolgst** [comment]
I do not understand

**Comment by TRDarthWader** [comment]
In this discord RPC package we have 2 buttons but I can't add secondary button for ex.
![IMG_20210604_051431](https://user-images.githubusercontent.com/53786706/120735708-c5d37a00-c4f3-11eb-80be-72ca9f1409e4.jpg)

**Comment by hugolgst** [comment]
I am sorry but have no idea what you are talking about
