### ISSUE TITLE
Discord Flatpak

### ISSUE THREAD

**Issue by Alxhr0** [hugolgst/rich-go#36]
Discord Flatpak now supports Discord RPC which can be enabled with

As a example i will take a plugin for a code editor called lite-xl which is called litepresence which adds discord rpc to it

mkdir -p ~/.config/user-tmpfiles.d echo 'L %t/discord-ipc-0 - - - - app/com.discordapp.Discord/discord-ipc-0' > ~/.config/user-tmpfiles.d/discord-rpc.conf systemctl --user enable --now systemd-tmpfiles-setup.service

But litepresence doesn't work with it because it searches for /run/user/1000/discord-ipc-0
the flatpak version has discord-ipc-0 in /run/user/1000/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-0

**Comment by rilysh** [comment]
I wonder, why you're even using flatpak version of Discord? Just download linux version from Discord's website and run through it.
