### ISSUE TITLE
Buttons doesnt work ?

### ISSUE THREAD

**Issue by celian-hamon** [hugolgst/rich-go#37]
```golang
	if player.State == "playing" {
		client.SetActivity(client.Activity{
			Details:    player.State + " " + player.Title,
			State:      "by " + player.Artist + " on " + player.Album,
			LargeImage: cover,
			LargeText:  player.Title,
			SmallImage: "https://res.cloudinary.com/dgpr0xv6x/image/upload/v1646949499/IMG_7462_ahqf1k.gif",
			SmallText:  player.State,
			Timestamps: &client.Timestamps{
				Start: &now,
				End:   &end,
			},
			Buttons: []*client.Button{
				{
					Label: "Made by Cece :)",
					Url:   "https://github.com/celian-hamon",
				},
			},
		})
    }
```

display : 

<img width="293" alt="image" src="https://user-images.githubusercontent.com/61624140/157854137-33e7ec53-0e65-4180-b148-77f31127b405.png">

but when i click on the button it doesnt redirect me ? Is this the discord sdk behaviour like it send a post and dont open the page ?

**Comment by celian-hamon** [comment]
works on my windows but not on m1 mac ?

**Comment by packet-sent** [comment]
> works on my windows but not on m1 mac ?

Weird for me it doesn't seem to work on windows anymore.

**Comment by celian-hamon** [comment]
works on my friends mac but not on mine ? and my work fine on my windows 10 ?

**Comment by packet-sent** [comment]
> works on my friends mac but not on mine ? and my work fine on my windows 10 ?

I found the issue 😅, according to discord you cannot click your own rich presence buttons, test it yourself with a second account.

**Comment by celian-hamon** [comment]
okay thank you :)
