### ISSUE TITLE
Time elapsed/started bug

### ISSUE THREAD

**Issue by dogesum** [hugolgst/rich-go#6]
I noticed the other day that my program that utilizes rich-go was a little bit broken. The 'time elapsed' function in my program wasn't working anymore. My Discord rich presence status was counting down, not up, even though I only provided a 'Start' value within my Timestamps struct. I double checked my code for any bugs on my part, but couldn't find any. I even tried switching applications in the Discord Developer Portal, but I still had the same result.

I decided to test the provided [example program](https://github.com/ananagame/rich-go/blob/master/example/main.go) in this repo to see if it would work correctly, but I couldn't get it to do so. I attached an excerpt from a slightly modified version of the example, and a photo of the result.

This is what my `client.SetActivity` code looks like:
```
err = client.SetActivity(client.Activity{
	err = client.SetActivity(client.Activity{
		State:   "Heyy!!!",
		Details: "I'm running on rich-go :)",
		Timestamps: &client.Timestamps{
			Start: time.Now(),
		},
	})
})
```

This is what my profile looks like under Discord:

![Screen Shot 2019-08-05 at 3 53 08 PM](https://user-images.githubusercontent.com/19379122/62496058-6001f400-b79d-11e9-9fc8-793792c40999.png)

**Comment by hugolgst** [comment]
I am going to look at this closely
